quiz-app/app/dashboard/forms.py
from wtforms.fields import StringField, PasswordField
from flask_wtf import FlaskForm
from wtforms.validators import ValidationError

from app.db import db
from app.modules.utils import check_password
from app.auth.forms import PasswordForm, ProfileForm
from flask import session

class QuizForm(FlaskForm):
    question = StringField(
        'question',
        render_kw={'class':'questions','placeholder':'Question','id':'question'}
    )
    a_option = StringField( 
        'A Option',
        render_kw={'class':'answer_option','placeholder':'A Option'}
    )
    b_option = StringField(render_kw={'class':'answer_option', 'placeholder':'B Option'})
    c_option = StringField(render_kw={'class':'answer_option', 'placeholder':'C Option'})
    d_option = StringField(render_kw={'placeholder':'D Option', 'class':'answer_option'})
    e_option = StringField(render_kw={'placeholder':'E Option', 'class':'E Option'})
    answer = StringField(render_kw={'placeholder':'answer (eg : A )', 'class':'answer'})

class ChangePwForm(FlaskForm, PasswordForm):
    old_password = PasswordField('old password')

    def validate_old_password(self, old_password):
        old_pw = db.users.find_one({'username':session.get('username')})
        if not old_pw or not check_password(old_pw.get('password'), old_password.data):
            raise ValidationError('invalid old password')

class DashProfile(ProfileForm, FlaskForm):
    pass 

quiz-app/app/dashboard/__init__.py
from flask import Blueprint

dashboard_blueprint = Blueprint('dashboard', __name__, url_prefix='/dashboard')

from .views import * 
from .admin import *

quiz-app/app/dashboard/views.py
from flask import (redirect, 
                   url_for, 
                   Response,
                   abort, 
                   render_template, 
                   session, 
                   request)

from app.dashboard.forms import QuizForm, ChangePwForm, DashProfile
from app.dashboard import dashboard_blueprint as dashboard 
from app.db import quiz, db
from app.modules.decorators import login_required
from app.modules.utils import json_decoder

import io, json 

@dashboard.route('/')
@login_required
def dashboard_index():
    return render_template('dashboard/index.html')


@dashboard.route('/quiz/download/<code>')
@login_required
def download_quiz(code):
    """
    function to export quiz from json to download for users
    """
    result = quiz.aggregate([
        {'$match':{
            'code':code
        }},
        {'$group':{
            '_id':'$code',
            'data':{
                '$first':'$data'
            }
        }}
    ])

    list_result = [_ for _ in result]
    if list_result:
        data_result = json.dumps(list_result[-1]['data'])
        
        return Response(
            io.StringIO(data_result), status=200,
            mimetype='application/json',
            headers={'Content-Disposition':'attachment;filename={}.json'.format(code)}
        )


@dashboard.route('/manage-quiz')
@login_required
def manage_quiz():

    author = {'$exists':True} if session.get('type') == 1 else session.get('username')

    result = [x for x in quiz.find({'author':author})]
    list_id = [x['code'] for x in result if x.get('code')]

    list_quiz = [x['quiz_title'] for x in result 
                for y in list_id 
                if x.get('code') == y]

    data = zip(list_quiz, list_id)
    
    return render_template('dashboard/manage-quiz.html', data=data)

@dashboard.route('/change-password')
@login_required
def change_password():
    form = ChangePwForm()

    return render_template('dashboard/change-password.html', form=form)

@dashboard.route('/edit-quiz/<code>')
@login_required
def edit_quiz(code):
    
    check = json_decoder(quiz.find_one({'code':code}))
    if check and (session.get('username') == check['author'] or session.get('type') == 1):
        forms = []
        for data in range(len(check['data'])):
            form = QuizForm()
            
            form.a_option.data = check['data'][data].get('a_option')
            form.b_option.data = check['data'][data].get('b_option')
            form.c_option.data = check['data'][data].get('c_option')
            form.d_option.data = check['data'][data].get('d_option')
            form.e_option.data = check['data'][data].get('e_option')
            form.question.data = check['data'][data].get('question')
            form.answer.data = check['data'][data].get('answer')
            forms.append(form)

        return render_template('dashboard/add-quizes.html', forms=forms)
    abort(403)

@dashboard.route('/profile')
@login_required
def profile_page():
    form = DashProfile()

    form.full_name.data = session.get('name')
    form.username.data = session.get('username')
    form.email.data = session.get('email')
    return render_template('dashboard/profile.html', form=form)

@dashboard.route('/delete-quiz/<code>')
@login_required
def delete_quiz(code):
    result = json_decoder(quiz.find_one({'code':code}))
    if result:
        if result.get('author') == session.get('username') or session.get('type') == 1:
            quiz.delete_one({'code':code})
    return redirect(url_for('dashboard.manage_quiz'))

@dashboard.route('/scores')
@login_required
def scores():
    return render_template('dashboard/users-scores.html')


@dashboard.route('/users-scores')
@login_required
def users_scores():
    return render_template('dashboard/users-scores.html')

@dashboard.route('/upload-quiz')
@login_required
def upload_quiz():
    return render_template('dashboard/csv-upload.html')

@dashboard.route('/logout')
@login_required
def logout():
    session.clear()
    return redirect(url_for('auth.login_page'))


@dashboard.route('/add-quizes')
@login_required
def add_quizes():
    form = QuizForm()
    return render_template('dashboard/add-quizes.html', form=form)


@dashboard.route('/export-quiz/<code>')
def export_quiz(code):
    check_exists = quiz.find_one({'code':code})
    if check_exists:
        resp = Response(json_decoder(check_exists), mimetype='application/csv')
        resp.headers['Content-Disposition'] = 'attachment: filename={}.csv'.format(code)
        resp.headers['Content-Length'] = len(check_exists)
        return resp
    return 'no'

quiz-app/app/templates/dashboard/add-quizes.html
<html>
    <head>
        {% include 'dashboard/includes/head.html' %}
        
    </head>
<body>
    {% include 'dashboard/includes/sidebar.html' %}
    {% extends 'dashboard/includes/content.html' %}

    {% block text_content %}
        <div id='question-box'>
            <p>
                ssttt.. you can <a href='{{url_for("dashboard.upload_quiz")}}'>upload your quiz from CSV!!</a>
            </p>
            <input type="text" name='quiz_title' placeholder="Question Title" class='questions' id='q'>

            {% if forms %}
                {% for data in forms %}
                    <div class='question-wrapper' style="margin-top: 12px;" id='question-wrapper'>
                        {{data.question}}
                        <div class='option-wrapper'>
                        <p>A. {{data.a_option}}</p>
                        <p>B. {{data.b_option}}</p>
                        <p>C. {{data.c_option}}</p>
                        <p>D. {{data.d_option}}</p>
                        <p>E. {{data.e_option}}</p>
                        <p> {{data.answer}}  </p>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            {% if form %}
            <div class='question-wrapper' style="margin-top: 12px;" id='question-wrapper'>
                <input type='text' name='question' class='questions' placeholder="Enter Question" id='question'>
                <div class='option-wrapper'>
                <p>A. {{form.a_option}}</p>
                <p>B. {{form.b_option}}</p>
                <p>C. {{form.c_option}}</p>
                <p>D. {{form.d_option}}</p>
                <p>E. {{form.e_option}}</p>
                <p> {{form.answer}}  </p>
                </div>
            </div>
            {% endif %}
        </div>
        <p>
            <a href='#' class='text-success' style="font-size: 20px;" id='addquest'>
                + add more questions
            </a>
        </p>
        <p>
            <button type='button' class='btn btn-outline-success' id='submitquest'>Submit</button>
        </p>
        <p id='message'></p>

    {% endblock %}
    {% include 'dashboard/includes/script.html' %}
    {% include 'extra/csrf.html' %}

</body>
</html>

quiz-app/app/templates/dashboard/change-password.html
<html>
    <head>
        {% include 'dashboard/includes/head.html' %}
    </head>
    <body>
        {% include 'dashboard/includes/sidebar.html' %}
        {% extends 'dashboard/includes/content.html' %}
        {% block text_content %}
            <p id='messages'></p>
            <lable for='old_password'>Old Password</lable>
            <p>{{form.old_password}}</p>
            <label for='password'>New Password</label>
            <p>{{form.password}}</p>
            <label for='password_confirmation'>
                Confirm Password
            </label>
            <p>{{form.password_confirmation}}</p>
            <p><button type='submit' class='btn btn-outline-dark' id='changepassword'>Gas kan</button></p>
        {% endblock %}
        {% include 'dashboard/includes/script.html' %}
        {% include 'extra/csrf.html' %}
    </body>
</html>

quiz-app/app/templates/dashboard/csv-upload.html
<html>
    <head>
        {% include 'dashboard/includes/head.html' %}
    </head>
<body>
    {% include 'dashboard/includes/sidebar.html' %}
    {% extends 'dashboard/includes/content.html' %}
    {% block text_content %}
        <div id='question-box'>
 
                <input type='text' name='quiz_title' class="questions" placeholder="Quiz Title" id='quiz_title'>
                <p>
                    <input type='file' id='csv' style="margin-top: 12px;">
                    <input type='submit' class="btn btn-outline-success" id='uploadquiz' value='Upload'>
                </p>
        </div>
        <p id='message'></p>
    {% endblock %}
    {% include 'dashboard/includes/script.html' %}
    {% include 'extra/csrf.html' %}
</body>
</html>

quiz-app/app/templates/dashboard/index.html
<html>
    <head>
        <title>
            Hello World
        </title>
        {% include 'extra/head.html' %}
        <link rel='stylesheet' href='{{url_for("static", filename="css/dashboard.css")}}'>
    </head>
<body>
    {% include 'dashboard/includes/sidebar.html' %}
    {% extends 'dashboard/includes/content.html' %}
    {% block text_content %}
        <p>Welcome! you can manage your own quizes here</p>
    {% endblock %}

    {% include 'dashboard/includes/script.html' %}
</body>
</html>

quiz-app/app/templates/dashboard/manage-quiz.html
<html>
    <head>
        <title>Manager Quiz</title>
        {% include 'extra/head.html' %}
        <link rel='stylesheet' href='{{url_for("static", filename="css/dashboard.css")}}'>
    </head>
<body>
    {% include 'dashboard/includes/sidebar.html' %}
    {% extends 'dashboard/includes/content.html' %}
    {% block text_content %}
        <table class='table table-responsive' id='table-quiz'>
            <thead>
                <tr>
                    <th>Quiz Name</th>
                    <th>Link</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for quiz, id in data %}
                    <tr>
                        <td>{{quiz}}</td>
                        <td>{{url_for("quiz.quiz_homepage", code=id, _external=True)}}</td>
                        <td>
                            <a href='{{url_for("dashboard.edit_quiz", code=id)}}' class='table-link'>Edit</a>
                            <a href='{{url_for("dashboard.download_quiz", code=id)}}' class='table-link'>Download</a>
                            <a href='{{url_for("dashboard.delete_quiz", code=id)}}' class='text-danger'>Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endblock %}
    {% include 'dashboard/includes/script.html' %}
</body>
</html>

quiz-app/app/templates/dashboard/profile.html
<html>
    <head>
        {% include 'dashboard/includes/head.html' %}
    </head>
<body>
    {% include 'dashboard/includes/sidebar.html' %}
    {% extends 'dashboard/includes/content.html' %}
    {% block text_content %}
    <p id='message'></p>
        <p>{{form.username}}</p>
        <p>{{form.full_name}}</p>
        <p>{{form.email}}</p>
        <p>
            <a href='#' class='btn btn-outline-dark' id='editprofile'>Submit</a>
        </p>
    {% endblock %}
    {% include 'dashboard/includes/script.html' %}
    {% include 'extra/csrf.html' %}
</body>
</html>

quiz-app/app/templates/dashboard/users-scores.html
<html>
    <head>
        {% include 'dashboard/includes/head.html'%}
    </head>
<body>
    {% include 'dashboard/includes/sidebar.html' %}
    {% extends 'dashboard/includes/content.html' %}
    {% block text_content %}
        <table id='scores-users' class='table table-responsive'>
            <thead>
                <tr>
                    <th>Done By</th>
                    <th>Score</th>
                    <th>Quiz Title</th>
                    <th>Date</th>
                </tr>
            </thead>
        </table>
    {% endblock %}
    {% include 'dashboard/includes/script.html' %}
</body>
</html>